### ISSUE TITLE
Individual Fee Misses Tax Split Calculation 7% / 19%

### ISSUE THREAD

**Issue by iq0n** [vendidero/woocommerce-germanized#129]
I have encountered the following issue (see attachments):

I have added a **fee, that must be taxable with 19%**, while the other products in the shop have a tax of 7%.
Germanized should split up both fees and show them in the cart. 

If you add products with 19% tax it shows up the splitted taxes in the cart and checkout as expected.

**But if you only add the 19% taxable fee it does not show the tax split. Currently it does only calculate 7% for everything.**

![tax_calculation_with_germanized](https://user-images.githubusercontent.com/11944743/107688735-41d95600-6ca8-11eb-8efd-072493b1ca1e.png)

After deactivating Germanized **the tax calculation as well as the correct representation (6€ including 19% tax)** works as expected but I do not want to deactivate Germanized of course.

![tax_calculation_without_germanized](https://user-images.githubusercontent.com/11944743/107688914-7a792f80-6ca8-11eb-97e8-537a54efd1ba.jpg)

I think the right starting point would be in this file: https://github.com/vendidero/woocommerce-germanized/blob/bcc92809ca07d1733f04c743433dbbce6209422b/includes/class-wc-gzd-checkout.php#L781

```
	/**
	 * @param $fee_taxes
	 * @param $fee
	 * @param WC_Cart_Totals $cart_totals
	 */
	public function adjust_fee_taxes( $fee_taxes, $fee, $cart_totals ) {

		if ( ! wc_gzd_enable_additional_costs_split_tax_calculation() ) {
			return $fee_taxes;
		}

		$calculate_taxes = wc_tax_enabled();

		// Do not calculate tax shares if tax calculation is disabled
		if ( ! $calculate_taxes ) {
			return $fee_taxes;
		}

---->>>  tax_shares = wc_gzd_get_cart_tax_share( 'fee' );

		/**
		 * Do not calculate fee taxes if tax shares are empty (e.g. zero-taxes only).
		 * In this case, remove fee taxes altogether.
		 */
		if ( empty( $tax_shares ) || WC()->customer->is_vat_exempt() ) {
			if ( wc_gzd_additional_costs_include_tax() ) {
				$total_tax  = array_sum( array_map( array( $this, 'round_line_tax_in_cents' ), $fee_taxes ) );
				$fee->total = $fee->total - $total_tax;

				/**
				 * In case the customer is a VAT exempt - use customer's tax rates
				 * to find the fee net price.
				 */
				if ( WC()->customer->is_vat_exempt() ) {
					$fee_rates  = WC_Tax::get_rates( '' );
					$fee_taxes  = WC_Tax::calc_inclusive_tax( $fee->total, $fee_rates );
					$fee->total = $fee->total - array_sum( $fee_taxes );
				}
			}

			return array();
		}
...
```

and this file: 
https://github.com/vendidero/woocommerce-germanized/blob/bcc92809ca07d1733f04c743433dbbce6209422b/includes/wc-gzd-cart-functions.php#L530
, due to the fact that the tax calculation only applies to cart items and not to "individual" fees.

```
        /**
         * Calculates tax share for shipping/fees
         *
         * @param string $type
         *
         * @return array
         */
        function wc_gzd_get_cart_tax_share( $type = 'shipping', $cart_contents = array() ) {
	        $cart        = empty( $cart_contents ) ? WC()->cart->cart_contents : $cart_contents;
	        $tax_shares  = array();
	        $item_totals = 0;
	        $is_cart     = true;
        
	        // Get tax classes and tax amounts
	        if ( ! empty( $cart ) ) {
------>>>	        foreach ( $cart as $key => $item ) {
```

I would highly appreciate it if you can provide me a code snippet/or push me in the right direction if a hook is possible to get this working. A sustainble solution would be of course a patch for that issue?

Btw.: I have deactivated all plugins and changed to a default theme before but that does not affect it.

Many thanks in advance!

**Comment by vendidero** [comment]
Hi there,

Germanized does ignore individual tax settings per fee and calculates fees for additional costs (fees, shipping) based on the tax rates included within the current cart. If the cart contains 7% products only, additional costs will be taxed the same way, ignoring any individual tax settings per fee. This is expected behavior. You might want to check back with your tax consultant on the issue. You might of course disable the split tax calculation option in Germanized > taxes > split tax alltogether though - this will enable the Woo default instead.

Cheers

**Comment by vendidero** [comment]
Hi there,

Germanized does ignore individual tax settings per fee and calculates fees for additional costs (fees, shipping) based on the tax rates included within the current cart. If the cart contains 7% products only, additional costs will be taxed the same way, ignoring any individual tax settings per fee. This is expected behavior. You might want to check back with your tax consultant on the issue. You might of course disable the split tax calculation option in Germanized > taxes > split tax alltogether though - this will enable the Woo default instead.

Cheers

**Comment by iq0n** [comment]
Works as expected, thanks a lot!
