### ISSUE TITLE
Remove action does not work

### ISSUE THREAD

**Issue by maxxscho** [vendidero/woocommerce-germanized#18]
I want to remove an action - for example [this](https://github.com/vendidero/woocommerce-germanized/blob/master/includes%2Fwc-gzd-template-hooks.php#L20) (the output for the shipping info should be on another place) with the following code in my functions.php:

````
remove_action( 'woocommerce_single_product_summary', 'woocommerce_gzd_template_single_legal_info', 11 );
````

I have tried many priorities and inserted the code on different positions in my theme. No way - it's always there.

**Comment by panploenes** [comment]
Same for me. Worked in previous releases. I am using init to hook the funciton.

**Comment by vendidero** [comment]
Hi,

as for the newest version available within the WP repo one has to use the same hook (woocommerce_before_main_content) to actually remove hooks (because this hook is being used by WC Germanized to add the hooks which applies later than your functions.php)

I've just added some fix to that in the latest commit. You may now override with your functions.php.
For the legal info hook one may use the following code:

remove_action( 'woocommerce_single_product_summary', 'woocommerce_gzd_template_single_legal_info', wc_gzd_get_hook_priority( 'single_legal_info' ) );

the wc_gzd_get_hook_priority function returns the current hooks' priority (this is being calculated dynamically based on your themes' hooks to woocommerce_template_single_price). Please mind that this function does currently only work for the single product unit price + single product legal info. For all other hooks the priorities are hardcoded within wc-gzd-template-hooks.php

Cheers
