### ISSUE TITLE
VAT display and questions

### ISSUE THREAD

**Issue by mariusmateoc** [vendidero/woocommerce-germanized#85]
Hi,

Wordpress: 4.9.7
WooCommerce: 3.4.4
WooCommerce Germanized: 2.0.4
WooCommerce Germanized Pro: 1.9.3

**1. Not showing the percent at the variable product in shop**
On the shop page single product shows incl. 19% VAT but the variable product, only incl VAT is displayed without actual percent. I think you choose that because you can set a tax class on each variation but when all variations have the tax class same as the parent. 
![image](https://user-images.githubusercontent.com/2094443/44082375-5233b94e-9fb1-11e8-86dc-e1d05aef4ede.png)

**2. Not showing excluding VAT**
For regular customer (without a valid VAT ID) in the mini cart, cart and checkout you show **incl. 19% VAT** and the amount on the summary, there is a reason why for a business client (with a valid VAT ID) you don't show **excl. 19% VAT** text after the total (or subtotal in the mini cart) as you show on shop and product page? I think adding this to the mini cart, cart and checkout will keep the users informed about the final price.

**3. Option not propagate on cart and checkout**
WooCommerce -> Settings -> Germanized -> Display Options -> Hide Tax Rate is checked to Hide specific tax rate within shop pages.
I don't know if this is intentional but with this option enabled on the mini cart, cart and checkout you show the percentage too (incl. 19% VAT) and not the only incl. VAT along with the amount. Don't know if by shop pages you exclude cart and checkout.

**4. Prices not showing right after order completed**
Having the options 
• WooCommerce -> Settings -> Germanized -> 
General Options -> VAT Check enabled
• WooCommerce -> Settings -> Germanized -> 
General Options -> VAT Check Login enabled

After I logged in as a client that has a valid VAT ID the prices are shown excluding tax as it should, then I complete an order after that from success page if I click on shop again (still logged in as a business client) the prices in the shop are shown with including tax and not excluding tax as it should, so I need to log out then log in again to see the prices excluding tax.

**5. This is not an issue with the plugin but a help request if you have time.**
I create another integration(partial for what I need) that works with woocommerce-germanized and I want to know what hook to use to integrate it without modifying the plugin. If you can provide an example it would be really helpful. Also, you can put it as knowledge in README.md to help less experienced developers.

Thanks,
Marius

**Comment by vendidero** [comment]
Hi there,

1. This is a performance-relevant issue as it can be quite costly to check all variations agains their tax rate. That's why we are stripping away the actual tax rate for variable products (which shouldn't be a legal problem)

2. Within cart/checkout no such notices are necessary as no tax is being added to the cart.

3. This is intentional. The layout options only affect single product page and/or listings.

4. We are currently working on this and will improve our implementation within our next pro release.

5. Integrations (or compatibility scripts) can be added via our filter "woocommerce_gzd_compatibilities". You may want to extend our base class "WC_GZD_Compatibility" and check our implementations within includes/compatibility for further information.

**Comment by Clarence344** [comment]
Hi, 
just overwrite in woocommerce-germanized/includes/abstracts/abstract-wc-gzd-product.php the line 549

$tax_notice = ( $tax_display_mode == 'incl' && ! $is_vat_exempt ? __( 'incl. VAT', 'woocommerce-germanized' ) : __( 'excl. VAT', 'woocommerce-germanized' ) );

with 

$tax_notice = ( $tax_display_mode == 'incl' && ! $is_vat_exempt ? sprintf( __( 'incl. %s%% VAT', 'woocommerce-germanized' ), ( wc_gzd_format_tax_rate_percentage( $tax_rates[0]['rate'] ) ) ) : sprintf( __( 'excl. %s%% VAT', 'woocommerce-germanized' ), ( wc_gzd_format_tax_rate_percentage( $tax_rates[0]['rate'] ) ) ) );

**Comment by Whitecitys** [comment]
Can we override by using child theme ?

> Hi, just overwrite in woocommerce-germanized/includes/abstracts/abstract-wc-gzd-product.php the line 549
> 
> $tax_notice = ( $tax_display_mode == 'incl' && ! $is_vat_exempt ? __( 'incl. VAT', 'woocommerce-germanized' ) : __( 'excl. VAT', 'woocommerce-germanized' ) );
> 
> with
> 
> $tax_notice = ( $tax_display_mode == 'incl' && ! $is_vat_exempt ? sprintf( __( 'incl. %s%% VAT', 'woocommerce-germanized' ), ( wc_gzd_format_tax_rate_percentage( $tax_rates[0]['rate'] ) ) ) : sprintf( __( 'excl. %s%% VAT', 'woocommerce-germanized' ), ( wc_gzd_format_tax_rate_percentage( $tax_rates[0]['rate'] ) ) ) );

**Comment by dennisnissle** [comment]
In short: Don't do it. In general it's much better/safer to show a general tax notice (shop-wide) instead of showing the actual percentage. If you really want to change it use the official filter: https://github.com/vendidero/woocommerce-germanized/blob/master/includes/abstracts/abstract-wc-gzd-product.php#L1269
