### ISSUE TITLE
Send payment notification after order not working

### ISSUE THREAD

**Issue by Johnny99211** [vendidero/woocommerce-germanized#87]
Hello,

I've tried to sent the payment notification email after the order is successfully paid but the do_action is not reachable for some reason. I can't find the problem. I'm skipping some order statuses so I need to send the payment notification with the filter to trigger it:

This is the email I'm talking about: [Payment Notification E-Mail](https://github.com/vendidero/woocommerce-germanized/blob/master/includes/emails/class-wc-gzd-email-customer-paid-for-order.php)

I've tried so much the last days and this is my last hope.

My code:

```
add_filter( 'woocommerce_payment_complete_order_status', 'update_order_status', 10, 2 );
function update_order_status( $order_status, $order_id ) {

    do_action( 'woocommerce_order_status_pending_to_processing_notification', $order_id );

    return 'completed';
}
```

**Comment by vendidero** [comment]
Hi,

sorry, I guess that issue was a little overseen. You should better use the following hook:

`woocommerce_payment_complete`

to send the email. You'll need to call the trigger directly e.g.:

`if ( $email = WC_germanized()->emails->get_email_instance_by_id( 'customer_paid_for_order' ) ) {
    $email->trigger( $order_id );
}`

Cheers
